--- 
    - name:  cambiar puerto ssh
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '#Port\ 22'
        line: Port 4444 

    - name: desactivar login root SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '#PermitRootLogin\ yes'
        line: PermitRootLogin no

    - name: desactivar password ssh
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "PasswordAuthentication\ yes"
        line: PasswordAuthentication no

    - name: restringir usuario ssh 
      ansible.builtin.lineinfile:
         path: /etc/ssh/ssd_config
         line: AllowUsers usuario
         create: yes

    - name: reiniciar ssh
      service:
        name: ssh
        state: restarted
        enabled: true
        
